# Generated by Django 5.0.6 on 2024-06-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Calzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=60)),
                ('talle', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Indumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=60)),
                ('talle', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
